name: issue-comment-CI-test 

on: 
  push:
    branches: [test-github-actions]
  issue_comment:    
jobs:   
  build:    

    runs-on: ubuntu-latest  

    steps:  
    - uses: actions/checkout@v1 
    - name: Run a one-line script   
      run: echo Hello, world!
